apiVersion: v1
kind: Pod
metadata:
  name: log-printer
spec:
  containers:
  - name: log-printer
    image: busybox:1.35
    command:
      - /bin/sh
      - -c
      - "while true; do echo $(date) - Log message; sleep 10; done"

